---
- name: Ensure nginx installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Render nginx site
  ansible.builtin.template:
    src: nginx-site.conf.j2
    dest: "/etc/nginx/sites-available/{{ role_iptvservice__nginx_site_name }}"
    mode: "0644"
  notify: reload nginx
  vars:
    all_server_names: >-
      {{
        (role_iptvservice__iptv_hostname | list)
        + (role_iptvservice__iptv_hostname | map('regex_replace','^(.*)$','iptv.\\1') | list)
        + (role_iptvservice__iptv_hostname | map('regex_replace','^(.*)$','test.\\1') | list)
      }}
    backend_ports: "{{ __backends | map(attribute='port') | list }}"

- name: Enable site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ role_iptvservice__nginx_site_name }}"
    dest: "/etc/nginx/sites-enabled/{{ role_iptvservice__nginx_site_name }}"
    state: link
  notify: reload nginx

- name: Disable default nginx site (if present)
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: nginx -t
  ansible.builtin.command: nginx -t
  register: __nginx_test
  changed_when: false

- name: Reload nginx if not yet
  ansible.builtin.meta: flush_handlers
