---

- name: Test Connect to Each Upstream Account with URI module
  ansible.builtin.uri:
    url: "{{ item.0.url }}/player_api.php?username={{ item.1.username }}&password={{ item.1.password }}"
    method: GET
    status_code: 200
  loop: "{{ role_iptvservice__credentials | subelements('provider_credentials') }}"
  loop_control:
    label: >-
      Checking {{ item.1.account }}:{{ item.1.username }} at {{ item.0.url }}
  register: __upstream_test_results
  ignore_errors: true
  no_log: false

- name: debug
  debug:
    msg:
      - '{{ item.json.user_info.auth }}'
  loop: '{{ __upstream_test_results.results }}'

- name: Report any failed upstream account connections
  ansible.builtin.debug:
    msg: "Failed to connect to upstream account {{ item.item.account }} at {{ item.item.url }} with username {{ item.item.username }}"
  when: item.json.user_info.auth != 1
  loop: "{{ __upstream_test_results.results }}"
  loop_control:
    label: >-
      Displaying {{ item.item.1.account }}:{{ item.item.1.username }} at {{ item.item.0.url }}


    # "json": {
    #         "server_info": {                                                                                                                                                                                                                                                "https_port": "443",
    #             "port": "80",
    #             "process": true,
    #             "rtmp_port": "30002",
    #             "server_protocol": "https",
    #             "time_now": "2025-08-06 19:00:54",
    #             "timestamp_now": 1754528454,
    #             "timezone": "Pacific/Easter",
    #             "url": "pinkpony.lol"
    #         },
    #         "user_info": {                                                                                                                                                                                                                                                  "active_cons": "1",
    #             "allowed_output_formats": [
    #                 "m3u8",
    #                 "ts"
    #             ],
    #             "auth": 1,                                                                                                                                                                                                                                                  "created_at": "1749476847",
    #             "exp_date": "1765284447",
    #             "is_trial": "0",
    #             "max_connections": "4",
    #             "message": "Less is more..",
    #             "password": "trixie454",                                                                                                                                                                                                                                    "status": "Active",
    #             "username": "mikec"
    #         }
    #     },
...
